version: "3.8"

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    command: gunicorn shorty.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    restart: unless-stopped
    image: redis/redis-stack:latest
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data
      - ./src/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
  rabbitmq_server:
    image: rabbitmq:3.9.29-management
    expose:
      - 5672
  celery:
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    command: celery -A shorty worker -l info
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - rabbitmq_server

volumes:
  postgres_data:
  static_volume:
  redis_data:
