# Generated by Django 4.2.1 on 2023-07-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_online',
        ),
    ]
