# Generated by Django 4.2.1 on 2023-05-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='email confirmed'),
        ),
    ]
