# Generated by Django 4.2.1 on 2023-05-12 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_link_long_link_link_short_link_alter_link_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 12, 2, 39, 59, 989884)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['long_link'], name='shortener_l_long_li_209e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['short_link'], name='shortener_l_short_l_6382a4_idx'),
        ),
    ]
