# Generated by Django 4.2.1 on 2023-05-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_link_options_link_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='user',
            new_name='user_profile',
        ),
    ]
