# Generated by Django 4.2.1 on 2023-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_rename_user_link_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
