# Generated by Django 4.2.1 on 2023-05-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_alter_link_short_link'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='link',
            name='shortener_l_short_l_6382a4_idx',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='short_link',
            new_name='alias',
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['alias'], name='shortener_l_alias_3aafaf_idx'),
        ),
    ]
