# Generated by Django 4.2.1 on 2023-05-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_remove_link_shortener_l_short_l_6382a4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.TextField(max_length=2000),
        ),
    ]
